name: Build Huawei SaA Bridge APK

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.10.2'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build Mainline Debug APK
      run: |
        ./gradlew assembleMainlineDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Gadgetbridge-HuaweiSaA-debug-apk
        path: app/build/outputs/apk/mainline/debug/*.apk
        retention-days: 14
